catalog:
  '@types/node': 24.6.2
  oxc-parser: 0.93.0
  oxc-resolver: 11.9.0
  oxlint: 1.19.0
  typescript: 5.9.3
  vitest: 3.2.4

catalogMode: strict

catalogs:
  consumer:
    oxc-parser: ^0.87.0
    oxc-resolver: ^11.6.0

overrides:
  oxc-parser: 'catalog:'
  oxc-resolver: 'catalog:'
