catalog:
  '@types/node': 25.5.0
  oxc-parser: 0.118.0
  oxc-resolver: 11.19.1
  oxlint: 1.55.0
  typescript: 5.9.3
  vitest: 4.1.0

catalogMode: strict

catalogs:
  consumer:
    oxc-parser: ^0.87.0
    oxc-resolver: ^11.6.0

overrides:
  oxc-parser: 'catalog:'
  oxc-resolver: 'catalog:'
