catalog:
  '@types/node': 24.3.1
  oxc-parser: 0.87.0
  oxc-resolver: 11.7.1
  oxlint: 1.14.0
  typescript: 5.9.2
  vitest: 3.2.4

catalogMode: strict

catalogs:
  consumer:
    oxc-parser: ^0.87.0
    oxc-resolver: ^11.6.0

overrides:
  oxc-parser: 'catalog:'
  oxc-resolver: 'catalog:'
